[package]
name = "receiver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
futures = "0.3.31"
common = {path = "../common"}
bincode = { version = "2.0.1", features = ["serde"] }
