[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde={version="1", default-features=false, features=["derive"]}
nalgebra = {version="0.33.2", default-features = false, features = ["libm-force"]}
