
// THIS CODE WAS AUTOGENERATED BY `inv_pend.ipynb`
pub use crate::filter::{LinearModel};
pub fn pendulum_model() -> LinearModel<3, 3> {
    LinearModel {
A: [[1.00337,0.067487,3.2455e-18],[0.0989065,1.00131,-1.76537e-18],[-0.000210249,0.0019752,0.985816]].into(),
B: [[-0.000703678,-0.0138882,0.0993109]].into(),
C: [[0.0,1.33582,0.0],[0.0,-0.000593267,13.2107],[47.1325,-8.2956e-05,-0.041478]].into(),
D: [[0.0,0.0,0.0]].into(),
Q: [[11.3019,25447.7,5.72621e-08],[25447.7,5.72988e+07,1.41671e-06],[1.19961e-08,1.4056e-06,0.000450151]].into(),
R: [[1e+10,0.0,0.0],[0.0,1e-08,0.0],[0.0,0.01,1e+10]].into(),       
    }
}

pub const WHEEL_TIME_CONSTANT: f32 = 0.700000;
pub const WHEEL_STATIC_GAIN: f32 = 330.000000;
pub const INERTIA_RATIO: f32 = 0.040073;
pub const RADIUS: f32 = 0.147000;
pub const GRAVITY: f32 = 9.81;

