
// THIS CODE WAS AUTOGENERATED BY `inv_pend.ipynb`
pub use crate::filter::{LinearModel};
pub fn pendulum_model() -> LinearModel<3, 3> {
    LinearModel {
A: [[0.996637,-0.0673371,3.37445e-20],[0.0986868,0.994701,-9.96888e-19],[-0.000209246,0.00199998,0.985816]].into(),
B: [[-0.00070288,-0.0138565,0.0993109]].into(),
C: [[0.0,1.33582,0.0],[0.0,-0.000593267,13.2107],[47.1325,-8.2956e-05,-0.041478]].into(),
D: [[0.0,0.0,0.0]].into(),
Q: [[11.3019,25447.7,4.81311e-08],[25447.7,5.72988e+07,1.41335e-06],[4.69845e-09,1.4026e-06,0.000450148]].into(),
R: [[1e+10,0.0,0.0],[0.0,1e-08,0.0],[0.0,0.01,1e+10]].into(),       
    }
}

pub const WHEEL_TIME_CONSTANT: f32 = 0.700000;
pub const WHEEL_STATIC_GAIN: f32 = 330.000000;
pub const INERTIA_RATIO: f32 = 0.040073;
pub const RADIUS: f32 = 0.147000;
pub const GRAVITY: f32 = 9.81;

